affected_areas_count = {
	'Central America': 9,
	'Mexico': 7,
	'Cuba': 6,
	'Florida': 6,
	'The Bahamas': 7,
	'Lesser Antilles': 4,
	'United States East Coast': 3,
	'Atlantic Canada': 3,
	'Northeastern United States': 2,
	'Jamaica': 4,
	'Cayman Islands': 1,
	'Bermuda': 2,
	'Texas': 4,
	'Tamaulipas': 1,
	'Yucatan Peninsula': 3,
	'Georgia': 1,
	'The Carolinas': 1,
	'Virginia': 1,
	'Southeastern United States': 1,
	'Southwestern Quebec': 1,
	'New England': 1,
	'Louisiana': 1,
	'Midwestern United States': 1,
	'The Caribbean': 8,
	'United States Gulf Coast': 6,
	'United States East coast': 1,
	'South Texas': 1,
	'Venezuela': 3,
	'Hispaniola': 1,
	'South Florida': 1,
	'Greater Antilles': 2,
	'Bahamas': 2,
	'Eastern United States': 1,
	'Ontario': 1,
	'Windward Islands': 1,
	'Nicaragua': 1,
	'Honduras': 1,
	'Antilles': 1,
	'Colombia': 1,
	'Cape Verde': 1,
	'British Virgin Islands': 1,
	'U.S. Virgin Islands': 1,
	'Virgin Islands': 1,
	'Puerto Rico': 1,
	'Dominican Republic': 1,
	'Turks and Caicos Islands': 1,
	'United States Gulf Coast (especially Florida Panhandle)': 1
}
