hurricanes = {'Cuba I': {'Names': 'Cuba I', 'Months': 'October', 'Years': 1924, 'Max_Sustained_Winds': 165,
                         'Areas_Affected': ['Central America', 'Mexico', 'Cuba', 'Florida', 'The Bahamas'],
                         'Damages': 'Damages not recorded', 'Deaths': 90},
              'San Felipe II Okeechobee': {'Names': 'San Felipe II Okeechobee', 'Months': 'September', 'Years': 1928,
                                           'Max_Sustained_Winds': 160,
                                           'Areas_Affected': ['Lesser Antilles', 'The Bahamas',
                                                              'United States East Coast', 'Atlantic Canada'],
                                           'Damages': 100000000.0, 'Deaths': 4000},
              'Bahamas': {'Names': 'Bahamas', 'Months': 'September', 'Years': 1932, 'Max_Sustained_Winds': 160,
                          'Areas_Affected': ['The Bahamas', 'Northeastern United States'],
                          'Damages': 'Damages not recorded', 'Deaths': 16},
              'Cuba II': {'Names': 'Cuba II', 'Months': 'November', 'Years': 1932, 'Max_Sustained_Winds': 175,
                          'Areas_Affected': ['Lesser Antilles', 'Jamaica', 'Cayman Islands', 'Cuba', 'The Bahamas',
                                             'Bermuda'], 'Damages': 40000000.0, 'Deaths': 3103},
              'CubaBrownsville': {'Names': 'CubaBrownsville', 'Months': 'August', 'Years': 1933,
                                  'Max_Sustained_Winds': 160,
                                  'Areas_Affected': ['The Bahamas', 'Cuba', 'Florida', 'Texas', 'Tamaulipas'],
                                  'Damages': 27900000.0, 'Deaths': 179},
              'Tampico': {'Names': 'Tampico', 'Months': 'September', 'Years': 1933, 'Max_Sustained_Winds': 160,
                          'Areas_Affected': ['Jamaica', 'Yucatan Peninsula'], 'Damages': 5000000.0, 'Deaths': 184},
              'Labor Day': {'Names': 'Labor Day', 'Months': 'September', 'Years': 1935, 'Max_Sustained_Winds': 185,
                            'Areas_Affected': ['The Bahamas', 'Florida', 'Georgia', 'The Carolinas', 'Virginia'],
                            'Damages': 'Damages not recorded', 'Deaths': 408},
              'New England': {'Names': 'New England', 'Months': 'September', 'Years': 1938, 'Max_Sustained_Winds': 160,
                              'Areas_Affected': ['Southeastern United States', 'Northeastern United States',
                                                 'Southwestern Quebec'], 'Damages': 306000000.0, 'Deaths': 682},
              'Carol': {'Names': 'Carol', 'Months': 'September', 'Years': 1953, 'Max_Sustained_Winds': 160,
                        'Areas_Affected': ['Bermuda', 'New England', 'Atlantic Canada'], 'Damages': 2000000.0,
                        'Deaths': 5},
              'Janet': {'Names': 'Janet', 'Months': 'September', 'Years': 1955, 'Max_Sustained_Winds': 175,
                        'Areas_Affected': ['Lesser Antilles', 'Central America'], 'Damages': 65800000.0,
                        'Deaths': 1023},
              'Carla': {'Names': 'Carla', 'Months': 'September', 'Years': 1961, 'Max_Sustained_Winds': 175,
                        'Areas_Affected': ['Texas', 'Louisiana', 'Midwestern United States'], 'Damages': 326000000.0,
                        'Deaths': 43},
              'Hattie': {'Names': 'Hattie', 'Months': 'October', 'Years': 1961, 'Max_Sustained_Winds': 160,
                         'Areas_Affected': ['Central America'], 'Damages': 60300000.0, 'Deaths': 319},
              'Beulah': {'Names': 'Beulah', 'Months': 'September', 'Years': 1967, 'Max_Sustained_Winds': 160,
                         'Areas_Affected': ['The Caribbean', 'Mexico', 'Texas'], 'Damages': 208000000.0, 'Deaths': 688},
              'Camille': {'Names': 'Camille', 'Months': 'August', 'Years': 1969, 'Max_Sustained_Winds': 175,
                          'Areas_Affected': ['Cuba', 'United States Gulf Coast'], 'Damages': 1420000000.0,
                          'Deaths': 259},
              'Edith': {'Names': 'Edith', 'Months': 'September', 'Years': 1971, 'Max_Sustained_Winds': 160,
                        'Areas_Affected': ['The Caribbean', 'Central America', 'Mexico', 'United States Gulf Coast'],
                        'Damages': 25400000.0, 'Deaths': 37},
              'Anita': {'Names': 'Anita', 'Months': 'September', 'Years': 1977, 'Max_Sustained_Winds': 175,
                        'Areas_Affected': ['Mexico'], 'Damages': 'Damages not recorded', 'Deaths': 11},
              'David': {'Names': 'David', 'Months': 'August', 'Years': 1979, 'Max_Sustained_Winds': 175,
                        'Areas_Affected': ['The Caribbean', 'United States East coast'], 'Damages': 1540000000.0,
                        'Deaths': 2068},
              'Allen': {'Names': 'Allen', 'Months': 'August', 'Years': 1980, 'Max_Sustained_Winds': 190,
                        'Areas_Affected': ['The Caribbean', 'Yucatan Peninsula', 'Mexico', 'South Texas'],
                        'Damages': 1240000000.0, 'Deaths': 269},
              'Gilbert': {'Names': 'Gilbert', 'Months': 'September', 'Years': 1988, 'Max_Sustained_Winds': 185,
                          'Areas_Affected': ['Jamaica', 'Venezuela', 'Central America', 'Hispaniola', 'Mexico'],
                          'Damages': 7100000000.0, 'Deaths': 318},
              'Hugo': {'Names': 'Hugo', 'Months': 'September', 'Years': 1989, 'Max_Sustained_Winds': 160,
                       'Areas_Affected': ['The Caribbean', 'United States East Coast'], 'Damages': 10000000000.0,
                       'Deaths': 107},
              'Andrew': {'Names': 'Andrew', 'Months': 'August', 'Years': 1992, 'Max_Sustained_Winds': 175,
                         'Areas_Affected': ['The Bahamas', 'Florida', 'United States Gulf Coast'],
                         'Damages': 26500000000.0, 'Deaths': 65},
              'Mitch': {'Names': 'Mitch', 'Months': 'October', 'Years': 1998, 'Max_Sustained_Winds': 180,
                        'Areas_Affected': ['Central America', 'Yucatan Peninsula', 'South Florida'],
                        'Damages': 6200000000.0, 'Deaths': 19325},
              'Isabel': {'Names': 'Isabel', 'Months': 'September', 'Years': 2003, 'Max_Sustained_Winds': 165,
                         'Areas_Affected': ['Greater Antilles', 'Bahamas', 'Eastern United States', 'Ontario'],
                         'Damages': 5370000000.0, 'Deaths': 51},
              'Ivan': {'Names': 'Ivan', 'Months': 'September', 'Years': 2004, 'Max_Sustained_Winds': 165,
                       'Areas_Affected': ['The Caribbean', 'Venezuela', 'United States Gulf Coast'],
                       'Damages': 23300000000.0, 'Deaths': 124},
              'Emily': {'Names': 'Emily', 'Months': 'July', 'Years': 2005, 'Max_Sustained_Winds': 160,
                        'Areas_Affected': ['Windward Islands', 'Jamaica', 'Mexico', 'Texas'], 'Damages': 1010000000.0,
                        'Deaths': 17},
              'Katrina': {'Names': 'Katrina', 'Months': 'August', 'Years': 2005, 'Max_Sustained_Winds': 175,
                          'Areas_Affected': ['Bahamas', 'United States Gulf Coast'], 'Damages': 125000000000.0,
                          'Deaths': 1836},
              'Rita': {'Names': 'Rita', 'Months': 'September', 'Years': 2005, 'Max_Sustained_Winds': 180,
                       'Areas_Affected': ['Cuba', 'United States Gulf Coast'], 'Damages': 12000000000.0, 'Deaths': 125},
              'Wilma': {'Names': 'Wilma', 'Months': 'October', 'Years': 2005, 'Max_Sustained_Winds': 185,
                        'Areas_Affected': ['Greater Antilles', 'Central America', 'Florida'], 'Damages': 29400000000.0,
                        'Deaths': 87},
              'Dean': {'Names': 'Dean', 'Months': 'August', 'Years': 2007, 'Max_Sustained_Winds': 175,
                       'Areas_Affected': ['The Caribbean', 'Central America'], 'Damages': 1760000000.0, 'Deaths': 45},
              'Felix': {'Names': 'Felix', 'Months': 'September', 'Years': 2007, 'Max_Sustained_Winds': 175,
                        'Areas_Affected': ['Nicaragua', 'Honduras'], 'Damages': 720000000.0, 'Deaths': 133},
              'Matthew': {'Names': 'Matthew', 'Months': 'October', 'Years': 2016, 'Max_Sustained_Winds': 165,
                          'Areas_Affected': ['Antilles', 'Venezuela', 'Colombia', 'United States East Coast',
                                             'Atlantic Canada'], 'Damages': 15100000000.0, 'Deaths': 603},
              'Irma': {'Names': 'Irma', 'Months': 'September', 'Years': 2017, 'Max_Sustained_Winds': 180,
                       'Areas_Affected': ['Cape Verde', 'The Caribbean', 'British Virgin Islands',
                                          'U.S. Virgin Islands', 'Cuba', 'Florida'], 'Damages': 64800000000.0,
                       'Deaths': 138},
              'Maria': {'Names': 'Maria', 'Months': 'September', 'Years': 2017, 'Max_Sustained_Winds': 175,
                        'Areas_Affected': ['Lesser Antilles', 'Virgin Islands', 'Puerto Rico', 'Dominican Republic',
                                           'Turks and Caicos Islands'], 'Damages': 91600000000.0, 'Deaths': 3057},
              'Michael': {'Names': 'Michael', 'Months': 'October', 'Years': 2018, 'Max_Sustained_Winds': 160,
                          'Areas_Affected': ['Central America',
                                             'United States Gulf Coast (especially Florida Panhandle)'],
                          'Damages': 25100000000.0, 'Deaths': 74}}
