hurricane_mortality_scale = {
	0: [],
	1: [{'Name': 'Cuba I', 'Month': 'October', 'Year': 1924, 'Max_Sustained_Wind': 165,
	     'Areas_Affected': ['Central America', 'Mexico', 'Cuba', 'Florida',
	                        'The Bahamas'], 'Damages': 'Damages not recorded',
	     'Deaths': 90}, {'Name': 'Bahamas', 'Month': 'September', 'Year': 1932,
	                     'Max_Sustained_Wind': 160, 'Areas_Affected': ['The Bahamas',
	                                                                   'Northeastern United States'],
	                     'Damages': 'Damages not recorded', 'Deaths': 16},
	    {'Name': 'Carol', 'Month': 'September', 'Year': 1953, 'Max_Sustained_Wind': 160,
	     'Areas_Affected': ['Bermuda', 'New England', 'Atlantic Canada'],
	     'Damages': 2000000.0, 'Deaths': 5},
	    {'Name': 'Carla', 'Month': 'September', 'Year': 1961, 'Max_Sustained_Wind': 175,
	     'Areas_Affected': ['Texas', 'Louisiana', 'Midwestern United States'],
	     'Damages': 326000000.0, 'Deaths': 43},
	    {'Name': 'Edith', 'Month': 'September', 'Year': 1971, 'Max_Sustained_Wind': 160,
	     'Areas_Affected': ['The Caribbean', 'Central America', 'Mexico',
	                        'United States Gulf Coast'], 'Damages': 25400000.0,
	     'Deaths': 37},
	    {'Name': 'Anita', 'Month': 'September', 'Year': 1977, 'Max_Sustained_Wind': 175,
	     'Areas_Affected': ['Mexico'], 'Damages': 'Damages not recorded', 'Deaths': 11},
	    {'Name': 'Andrew', 'Month': 'August', 'Year': 1992, 'Max_Sustained_Wind': 175,
	     'Areas_Affected': ['The Bahamas', 'Florida', 'United States Gulf Coast'],
	     'Damages': 26500000000.0, 'Deaths': 65},
	    {'Name': 'Isabel', 'Month': 'September', 'Year': 2003,
	     'Max_Sustained_Wind': 165,
	     'Areas_Affected': ['Greater Antilles', 'Bahamas', 'Eastern United States',
	                        'Ontario'], 'Damages': 5370000000.0, 'Deaths': 51},
	    {'Name': 'Emily', 'Month': 'July', 'Year': 2005, 'Max_Sustained_Wind': 160,
	     'Areas_Affected': ['Windward Islands', 'Jamaica', 'Mexico', 'Texas'],
	     'Damages': 1010000000.0, 'Deaths': 17},
	    {'Name': 'Wilma', 'Month': 'October', 'Year': 2005, 'Max_Sustained_Wind': 185,
	     'Areas_Affected': ['Greater Antilles', 'Central America', 'Florida'],
	     'Damages': 29400000000.0, 'Deaths': 87},
	    {'Name': 'Dean', 'Month': 'August', 'Year': 2007, 'Max_Sustained_Wind': 175,
	     'Areas_Affected': ['The Caribbean', 'Central America'],
	     'Damages': 1760000000.0, 'Deaths': 45},
	    {'Name': 'Michael', 'Month': 'October', 'Year': 2018, 'Max_Sustained_Wind': 160,
	     'Areas_Affected': ['Central America',
	                        'United States Gulf Coast (especially Florida Panhandle)'],
	     'Damages': 25100000000.0, 'Deaths': 74}],
	2: [
		{'Name': 'CubaBrownsville', 'Month': 'August', 'Year': 1933, 'Max_Sustained_Wind': 160,
		 'Areas_Affected': ['The Bahamas', 'Cuba', 'Florida', 'Texas', 'Tamaulipas'],
		 'Damages': 27900000.0, 'Deaths': 179},
		{'Name': 'Tampico', 'Month': 'September', 'Year': 1933, 'Max_Sustained_Wind': 160,
		 'Areas_Affected': ['Jamaica', 'Yucatan Peninsula'], 'Damages': 5000000.0,
		 'Deaths': 184},
		{'Name': 'Labor Day', 'Month': 'September', 'Year': 1935, 'Max_Sustained_Wind': 185,
		 'Areas_Affected': ['The Bahamas', 'Florida', 'Georgia', 'The Carolinas', 'Virginia'],
		 'Damages': 'Damages not recorded', 'Deaths': 408},
		{'Name': 'Hattie', 'Month': 'October', 'Year': 1961, 'Max_Sustained_Wind': 160,
		 'Areas_Affected': ['Central America'], 'Damages': 60300000.0, 'Deaths': 319},
		{'Name': 'Camille', 'Month': 'August', 'Year': 1969, 'Max_Sustained_Wind': 175,
		 'Areas_Affected': ['Cuba', 'United States Gulf Coast'], 'Damages': 1420000000.0,
		 'Deaths': 259},
		{'Name': 'Allen', 'Month': 'August', 'Year': 1980, 'Max_Sustained_Wind': 190,
		 'Areas_Affected': ['The Caribbean', 'Yucatan Peninsula', 'Mexico', 'South Texas'],
		 'Damages': 1240000000.0,
		 'Deaths': 269},
		{'Name': 'Gilbert', 'Month': 'September', 'Year': 1988, 'Max_Sustained_Wind': 185,
		 'Areas_Affected': ['Jamaica', 'Venezuela', 'Central America', 'Hispaniola', 'Mexico'],
		 'Damages': 7100000000.0, 'Deaths': 318},
		{'Name': 'Hugo', 'Month': 'September', 'Year': 1989, 'Max_Sustained_Wind': 160,
		 'Areas_Affected': ['The Caribbean', 'United States East Coast'],
		 'Damages': 10000000000.0, 'Deaths': 107},
		{'Name': 'Ivan', 'Month': 'September', 'Year': 2004, 'Max_Sustained_Wind': 165,
		 'Areas_Affected': ['The Caribbean', 'Venezuela', 'United States Gulf Coast'],
		 'Damages': 23300000000.0,
		 'Deaths': 124},
		{'Name': 'Rita', 'Month': 'September', 'Year': 2005, 'Max_Sustained_Wind': 180,
		 'Areas_Affected': ['Cuba', 'United States Gulf Coast'], 'Damages': 12000000000.0,
		 'Deaths': 125},
		{'Name': 'Felix', 'Month': 'September', 'Year': 2007, 'Max_Sustained_Wind': 175,
		 'Areas_Affected': ['Nicaragua', 'Honduras'], 'Damages': 720000000.0, 'Deaths': 133},
		{'Name': 'Irma', 'Month': 'September', 'Year': 2017, 'Max_Sustained_Wind': 180,
		 'Areas_Affected': ['Cape Verde', 'The Caribbean', 'British Virgin Islands',
		                    'U.S. Virgin Islands', 'Cuba',
		                    'Florida'], 'Damages': 64800000000.0, 'Deaths': 138}],
	3: [
		{'Name': 'New England', 'Month': 'September', 'Year': 1938, 'Max_Sustained_Wind': 160,
		 'Areas_Affected': ['Southeastern United States', 'Northeastern United States',
		                    'Southwestern Quebec'],
		 'Damages': 306000000.0, 'Deaths': 682},
		{'Name': 'Beulah', 'Month': 'September', 'Year': 1967, 'Max_Sustained_Wind': 160,
		 'Areas_Affected': ['The Caribbean', 'Mexico', 'Texas'], 'Damages': 208000000.0,
		 'Deaths': 688},
		{'Name': 'Matthew', 'Month': 'October', 'Year': 2016, 'Max_Sustained_Wind': 165,
		 'Areas_Affected': ['Antilles', 'Venezuela', 'Colombia', 'United States East Coast',
		                    'Atlantic Canada'],
		 'Damages': 15100000000.0, 'Deaths': 603}],
	4: [
		{'Name': 'San Felipe II Okeechobee', 'Month': 'September', 'Year': 1928,
		 'Max_Sustained_Wind': 160,
		 'Areas_Affected': ['Lesser Antilles', 'The Bahamas', 'United States East Coast',
		                    'Atlantic Canada'],
		 'Damages': 100000000.0, 'Deaths': 4000},
		{'Name': 'Cuba II', 'Month': 'November', 'Year': 1932, 'Max_Sustained_Wind': 175,
		 'Areas_Affected': ['Lesser Antilles', 'Jamaica', 'Cayman Islands', 'Cuba',
		                    'The Bahamas', 'Bermuda'],
		 'Damages': 40000000.0, 'Deaths': 3103},
		{'Name': 'Janet', 'Month': 'September', 'Year': 1955, 'Max_Sustained_Wind': 175,
		 'Areas_Affected': ['Lesser Antilles', 'Central America'], 'Damages': 65800000.0,
		 'Deaths': 1023},
		{'Name': 'David', 'Month': 'August', 'Year': 1979, 'Max_Sustained_Wind': 175,
		 'Areas_Affected': ['The Caribbean', 'United States East coast'],
		 'Damages': 1540000000.0, 'Deaths': 2068},
		{'Name': 'Katrina', 'Month': 'August', 'Year': 2005, 'Max_Sustained_Wind': 175,
		 'Areas_Affected': ['Bahamas', 'United States Gulf Coast'], 'Damages': 125000000000.0,
		 'Deaths': 1836},
		{'Name': 'Maria', 'Month': 'September', 'Year': 2017, 'Max_Sustained_Wind': 175,
		 'Areas_Affected': ['Lesser Antilles', 'Virgin Islands', 'Puerto Rico',
		                    'Dominican Republic',
		                    'Turks and Caicos Islands'], 'Damages': 91600000000.0,
		 'Deaths': 3057}],
	5: [
		{'Name': 'Mitch', 'Month': 'October', 'Year': 1998, 'Max_Sustained_Wind': 180,
		 'Areas_Affected': ['Central America', 'Yucatan Peninsula', 'South Florida'],
		 'Damages': 6200000000.0,
		 'Deaths': 19325}]
}
